export type GenusDictionaryEntry = {
  genus: string;
  displayName: string;
  displayNamePlural: string;
};


export const GENUS_DICTIONARY: GenusDictionaryEntry[] = [
  { genus: 'Abies', displayName: 'Tanne', displayNamePlural: 'Tannen' },
  { genus: 'Acer', displayName: 'Ahorn', displayNamePlural: 'Ahorne' },
  { genus: 'Aesculus', displayName: 'Rosskastanie', displayNamePlural: 'Rosskastanien' },
  { genus: 'Ailanthus', displayName: 'Götterbaum', displayNamePlural: 'Götterbäume' },
  { genus: 'Alnus', displayName: 'Erle', displayNamePlural: 'Erlen' },
  { genus: 'Amelanchier', displayName: 'Felsenbirne', displayNamePlural: 'Felsenbirnen' },
  { genus: 'Betula', displayName: 'Birke', displayNamePlural: 'Birken' },
  { genus: 'Carpinus', displayName: 'Hainbuche', displayNamePlural: 'Hainbuchen' },
  { genus: 'Castanea', displayName: 'Kastanie', displayNamePlural: 'Kastanien' },
  { genus: 'Catalpa', displayName: 'Trompetenbaum', displayNamePlural: 'Trompetenbäume' },
  { genus: 'Cedrus', displayName: 'Zeder', displayNamePlural: 'Zedern' },
  { genus: 'Celtis', displayName: 'Zürgelbaum', displayNamePlural: 'Zürgelbäume' },
  { genus: 'Cercidiphyllum', displayName: 'Kuchenbaum', displayNamePlural: 'Kuchenbäume' },
  { genus: 'Cercis', displayName: 'Judasbaum', displayNamePlural: 'Judasbäume' },
  { genus: 'Chamaecyparis', displayName: 'Scheinzypresse', displayNamePlural: 'Scheinzypressen' },
  { genus: 'Colutea', displayName: 'Blasenstrauch', displayNamePlural: 'Blasensträucher' },
  { genus: 'Cornus', displayName: 'Hartriegel', displayNamePlural: 'Hartriegel' },
  { genus: 'Corylus', displayName: 'Hasel', displayNamePlural: 'Haseln' },
  { genus: 'Cotinus', displayName: 'Perückenstrauch', displayNamePlural: 'Perückensträucher' },
  { genus: 'Crataegus', displayName: 'Weißdorn', displayNamePlural: 'Weißdorne' },
  { genus: 'Cydonia', displayName: 'Cydonia', displayNamePlural: 'Cydonia' },
  { genus: 'Davidia', displayName: 'Taschentuchbaum', displayNamePlural: 'Taschentuchbäume' },
  { genus: 'Elaeagnus', displayName: 'Ölweide', displayNamePlural: 'Ölweiden' },
  { genus: 'Euodia', displayName: 'Stinkesche', displayNamePlural: 'Stinkeschen' },
  { genus: 'Euonymus', displayName: 'Spindelstrauch', displayNamePlural: 'Spindelsträucher' },
  { genus: 'Fagus', displayName: 'Buche', displayNamePlural: 'Buchen' },
  { genus: 'Fraxinus', displayName: 'Esche', displayNamePlural: 'Eschen' },
  { genus: 'Ginkgo', displayName: 'Ginkgo', displayNamePlural: 'Ginkgos' },
  { genus: 'Gleditsia', displayName: 'Gleditschie', displayNamePlural: 'Gleditschien' },
  { genus: 'Gymnocladus', displayName: 'Geweihbaum', displayNamePlural: 'Geweihbäume' },
  { genus: 'Hibiscus', displayName: 'Hibiskus', displayNamePlural: 'Hibisken' },
  { genus: 'Ilex', displayName: 'Stechpalme', displayNamePlural: 'Stechpalmen' },
  { genus: 'Juglans', displayName: 'Walnuss', displayNamePlural: 'Walnüsse' },
  { genus: 'Juniperus', displayName: 'Wacholder', displayNamePlural: 'Wacholder' },
  { genus: 'Koelreuteria', displayName: 'Blasenbaum', displayNamePlural: 'Blasenbäume' },
  { genus: 'Laburnum', displayName: 'Goldregen', displayNamePlural: 'Goldregen' },
  { genus: 'Larix', displayName: 'Lärche', displayNamePlural: 'Lärchen' },
  { genus: 'Liquidambar', displayName: 'Amberbaum', displayNamePlural: 'Amberbäume' },
  { genus: 'Liriodendron', displayName: 'Tulpenbaum', displayNamePlural: 'Tulpenbäume' },
  { genus: 'Magnolia', displayName: 'Magnolie', displayNamePlural: 'Magnolien' },
  { genus: 'Malus', displayName: 'Apfel', displayNamePlural: 'Äpfel' },
  { genus: 'Mespilus', displayName: 'Mispel', displayNamePlural: 'Mispeln' },
  { genus: 'Metasequoia', displayName: 'Urweltmammutbaum', displayNamePlural: 'Urweltmammutbäume' },
  { genus: 'Morus', displayName: 'Maulbeere', displayNamePlural: 'Maulbeeren' },
  { genus: 'Nothofagus', displayName: 'Scheinbuche', displayNamePlural: 'Scheinbuchen' },
  { genus: 'Nyssa', displayName: 'Tupelobaum', displayNamePlural: 'Tupelobäume' },
  { genus: 'Ostrya', displayName: 'Hopfenbuche', displayNamePlural: 'Hopfenbucen' },
  { genus: 'Parrotia', displayName: 'Eisenbaum', displayNamePlural: 'Eisenbäume' },
  { genus: 'Paulownia', displayName: 'Paulownie', displayNamePlural: 'Paulownien' },
  { genus: 'Phellodendron', displayName: 'Korkbaum', displayNamePlural: 'Korkbäume' },
  { genus: 'Picea', displayName: 'Fichte', displayNamePlural: 'Fichten' },
  { genus: 'Pinus', displayName: 'Kiefer', displayNamePlural: 'Kiefern' },
  { genus: 'Platanus', displayName: 'Platane', displayNamePlural: 'Platanen' },
  { genus: 'Populus', displayName: 'Pappel', displayNamePlural: 'Pappeln' },
  { genus: 'Prunus', displayName: 'Kirsche', displayNamePlural: 'Kirschen' },
  { genus: 'Pseudotsuga', displayName: 'Douglasie', displayNamePlural: 'Douglasien' },
  { genus: 'Ptelea', displayName: 'Kleeulme', displayNamePlural: 'Kleeulmen' },
  { genus: 'Pterocarya', displayName: 'Flügelnuss', displayNamePlural: 'Flügelnüsse' },
  { genus: 'Pyrus', displayName: 'Birne', displayNamePlural: 'Birnen' },
  { genus: 'Quercus', displayName: 'Eiche', displayNamePlural: 'Eichen' },
  { genus: 'Rhamnus', displayName: 'Kreuzdorn', displayNamePlural: 'Kreuzdorne' },
  { genus: 'Rhus', displayName: 'Rhus', displayNamePlural: 'Rhus' },
  { genus: 'Robinia', displayName: 'Robinie', displayNamePlural: 'Robinien' },
  { genus: 'Salix', displayName: 'Weide', displayNamePlural: 'Weiden' },
  { genus: 'Sambucus', displayName: 'Holunder', displayNamePlural: 'Holunder' },
  { genus: 'Sequoiadendron', displayName: 'Riesenmammutbaum', displayNamePlural: 'Riesenmammutbäume' },
  { genus: 'Sophora', displayName: 'Schnurbaum', displayNamePlural: 'Schnurbäume' },
  { genus: 'Sorbaria', displayName: 'Fiederspiere', displayNamePlural: 'Fiederspiere' },
  { genus: 'Sorbus', displayName: 'Mehlbeere', displayNamePlural: 'Mehlbeeren' },
  { genus: 'Syringa', displayName: 'Flieder', displayNamePlural: 'Flieder' },
  { genus: 'Taxodium', displayName: 'Sumpfzypresse', displayNamePlural: 'Sumpfzypressen' },
  { genus: 'Taxus', displayName: 'Eibe', displayNamePlural: 'Eiben' },
  { genus: 'Thuja', displayName: 'Lebensbaum', displayNamePlural: 'Lebensbäume' },
  { genus: 'Tilia', displayName: 'Linde', displayNamePlural: 'Linden' },
  { genus: 'Tsuga', displayName: 'Hemlocktanne', displayNamePlural: 'Hemlocktannen' },
  { genus: 'Ulmus', displayName: 'Ulme', displayNamePlural: 'Ulmen' },
  { genus: 'Zelkova', displayName: 'Zelkove', displayNamePlural: 'Zelkoven' },
];
